export const types = {
  LOGIN: '[Auth] Login',
  LOGOUT: '[Auth] Logout',
  UISETERROR: '[UI] Set Error',
  UIREMOVEERROR: '[UI] Remove Error',
  UISTARTLOADING: '[UI] Start Loading',
  UISTOPLOADING: '[UI] Stop Loading',
  NOTESADD: '[Notes] Add Note',
  NOTESACTIVE: '[Notes] Set Active Note',
  NOTESLOAD: '[Notes] Load Notes',
  NOTESUPDATED: '[Notes] Update Note',
  NOTESFILEURL: '[Notes] Update Image Url',
  NOTESDELETE: '[Notes] Delete Note',
  NOTESLOGOUTCLEAN: '[Notes] Logout clean',
};
